# Generated by Django 4.0.2 on 2022-07-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_title',
            field=models.CharField(max_length=500),
        ),
    ]
