# Generated by Django 4.0.2 on 2022-07-04 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0002_alter_track_track_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackWeight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.track')),
            ],
        ),
        migrations.CreateModel(
            name='ListenHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listen_time', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.track')),
            ],
        ),
    ]
