# Generated by Django 4.0.2 on 2022-07-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0008_uniformify_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenhistory',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
